

CREATE TABLE applications 
(
	id 			INT(11) 	NOT NULL 	AUTO_INCREMENT,
	domain 		VARCHAR(50) NULL 		DEFAULT NULL,
	name 		VARCHAR(50) NULL 		DEFAULT NULL,
	entity 		VARCHAR(50) NULL 		DEFAULT NULL
) ENGINE=InnoDB;